# Generated by Django 5.0.1 on 2024-04-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0029_rename_cemail_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('prefered_age_group', models.CharField(max_length=30, null=True)),
                ('keywords', models.CharField(max_length=130, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.customer')),
            ],
        ),
    ]
