# Generated by Django 5.0.1 on 2024-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0030_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='requested', max_length=20),
        ),
    ]
