# Generated by Django 5.0.1 on 2024-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0031_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
