# Generated by Django 5.0.1 on 2024-04-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0033_confirmedrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('share', models.CharField(max_length=100, null=True)),
                ('linkBasedinteraction', models.CharField(max_length=100, null=True)),
                ('keywordBasedinteraction', models.CharField(max_length=100, null=True)),
                ('ageBasedinteraction', models.CharField(max_length=100, null=True)),
                ('ConfirmedRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.confirmedrequest')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.customer')),
            ],
        ),
    ]
