# Generated by Django 5.0.4 on 2024-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0034_adminreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedrequest',
            name='adimage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='request',
            name='adimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
