# Generated by Django 5.0.1 on 2024-04-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0036_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
